# docker-compose.yml
version: "3.7"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

# pgadmin-compose:
#       image:dpage/pgadmin4
#          environment:
#          PGADMIN_DEFAULT_EMAIL:""
#          PGADMIN_DEFAULT_PASSWORD:"admin1234"
#          ports:
#               -"5432":"5432"
#               depends_on:
#                      - postgres